checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - src/*

build:
    nodes:
        php74:
            environment:
                php:
                    version: 7.4
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: vendor/bin/phpunit --coverage-clover=coverage74.xml
                        coverage:
                            file: coverage74.xml
                            format: php-clover
        php80:
            environment:
                php:
                    version: 8.0
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage80.xml
                        coverage:
                            file: coverage80.xml
                            format: php-clover
