checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths:
        - src/*

build:
    nodes:
        php83:
            environment:
                php:
                    version: 8.3
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover=coverage83.xml
                        coverage:
                            file: coverage83.xml
                            format: php-clover

